### ISSUE TITLE
Pregunta respecto a branch y yapa

### ISSUE THREAD

**Issue by redBaron23** [frlp-utn-ingsoft/filmster#11]
Hola, tengo las siguientes dudas hice un pull y queria ver como esta el tema con las branches, y me sale asi, solo pude identificar la verde que es el master, pero las dos rojas y la azul, como hago para saber?
Y de yapa, como elijo el label de las preguntas que hago por aca?

Saludos

![image](https://user-images.githubusercontent.com/23110463/56325544-ffe13680-6148-11e9-8025-7fcbe311c463.png)

**Comment by RodrigoJacznik** [comment]
Hola,
Cuando realizas un `pull` en realidad estas haciendo primero un `fetch` [doc](https://www.atlassian.com/git/tutorials/syncing/git-fetch) y luego un `merge` [doc](https://www.atlassian.com/git/tutorials/using-branches/git-merge).

Git cada vez que hace un `merge` por default lo intenta hacer un *fast foward merge* [doc](https://sandofsky.com/images/fast_forward.pdf). Esto "significa" que si es posible en lugar de dejar 2 branches, los unifica en 1 solo. Por esta razón no se ven todos los branches.

El branch de color rojo es el master pero tambien contiene integrado *alert_b_agregar* y *func_borrar*.

Para evitar que se utilize fast foward pueden usar la opción `--no-ff`

`git pull --no-ff`
`git merge --no-ff branch`

**Comment by redBaron23** [comment]
Gracias!
