### ISSUE TITLE
Duda extra a la actividad en proceso

### ISSUE THREAD

**Issue by MatiArea** [frlp-utn-ingsoft/filmster#22]
Hola! como están? Con el grupo hemos finalizado la actividad 2, por lo lo que ya tenemos en master la versión 1.2. Revisando el código, vimos que podríamos haber hecho una parte de la tarea opcional de otra manera mas amigable para el usuario. Nosotros podríamos agregar ese cambio al proyecto sin hacer un nuevo commit? O lo podemos agregar directamente en otra actividad?. 
Habíamos pensado hacer un checkout con el hash del commit antes de mergear con master y hacer un commit amend agregando el archivo que modificamos, pero lo que no sabemos es si cuando estamos sobre la rama master y hacemos el pull, si vamos a tener ese cambio reflejado. 
Gracias de antemano.

**Comment by RodrigoJacznik** [comment]
Buenas.

Podrían hacer las mejoras siguiendo gitflow. Esta es la mejor forma.

Si quieren seguir agregándole cosas a la app no hay problema. La actividad 2 es la ultima en la que se le agregan features.

Si tienen alguna duda de como resolver las cosas también nos pueden preguntar.

Saludos y sigan así que están haciendo un muy buen trabajo :+1:  :muscle:

**Comment by MatiArea** [comment]
Perfecto, muchas gracias! Saludos
