### ISSUE TITLE
Problema con rama vieja

### ISSUE THREAD

**Issue by juanpablomoscoloni** [frlp-utn-ingsoft/filmster#24]
Hola chicos como andan? Bueno paso a contarles, estaba terminando el punto 3 y necesitaba la rama donde estaba mergeado el hotfix para probarlo. El hotfix lo mergeo un compañero mio con dev y con master. A todos les funciona bien. Menos a mi.
El problema está en que entraba a dev y no estaba el bug arreglado, pero para el resto de mis compañeros si. Nosotros la vez anterior habiamos borrado su dev y creamos uno llamado develop. Este lunes en clase me hicieron pasar todo a dev, me ayudaron y lo pase todo a dev. Pero resulta que el cambio que todos mis compañero tienen en su rama dev, yo lo tengo en la rama develop, cual es el motivo? Y como podrá resolverlo? 
Un saludo!

**Comment by ivanduva** [comment]
Buenas. Vi su repo y el hotfix está tanto en master como en dev. Vos lo que tenés que hacer es git pull origin dev, parado en dev.

Saludos
