### ISSUE TITLE
Consulta sobre features

### ISSUE THREAD

**Issue by azamma** [frlp-utn-ingsoft/filmster#27]
Buenas. 

Si una rama feature fue mergeada al dev y después nos encontramos con un error, la modificación se hace de nuevo en la feature y se mergea otra vez? O se puede corregir el error directamente en la dev?

Saludos.

**Comment by ivanduva** [comment]
Buenas,
Es una muy buena pregunta. Por ahí puede haber varias interpretaciones, pero yo haría otro branch con el bugfix, saliendo desde dev.

Saludos!
