### ISSUE TITLE
Consulta sobre Eliminar

### ISSUE THREAD

**Issue by pessotanoariel** [frlp-utn-ingsoft/filmster#29]
Buenas! Como va? Me podrían pasar el código del Eliminar una película? 
Saludos!

**Comment by ivanduva** [comment]
buenas,
En el service (api.js del lado del cliente) tienen que pegarle al endpoint api/v1/movies de la siguiente manera:
```
function delete(id) {
    return fetch('/api/v1/movies/' + id,
        { method: 'DELETE' })
        .then(function(response) {
            return response;
        })
        .then(function(response) {
            // Acá pueden hacer lo que consideren necesario(por ejemplo, refrescar la página)
            console.log(response)
        })
        .catch(function(error) {
            console.log(error)
        });
}
```
Luego, llaman a esa función desde el método para borrar que ustedes ya crearon en index.mjs

Saludos

**Comment by pessotanoariel** [comment]
Perdón que pregunte otra vez. Pero no me funciona. Ahí les paso mi código.
En client/api/movie.mjs quedaría así:

`function getAll() {
    return fetch('/api/v1/movies')
        .then(result => result.json())
}

function deleteMovie(id) {

    return fetch('/api/v1/movies/' + id,

        { method: 'DELETE' })

        .then(function(response) {

            return response;

        })

        .then(function(response) {

            location.reload();

            console.log(response)

        })

        .catch(function(error) {

            console.log(error)

        });

}


export default {
    getAll, deleteMovie
}`

Tuve que llamarlo deleteMovie porque delete no funcionaba.
Y en client/index.mjs cuando la llamo me aparece un error

`function borrarPelicula(){

        movieService.deleteMovie(id);

    }    
` 
El borrarPelicula funciona. Tengo el botón referenciado y con un listener. El error me lo marca en el parámetro id del deleteMovie.

Saludos!

**Comment by ivanduva** [comment]
eso es porque no le estas pasando el id de la película que quieren que se borre. Deberían llamar a esta función para obtenerlo: 
`table.getSelectedRows();`
eso te debería devolver un array con las películas seleccionadas

**Comment by pessotanoariel** [comment]
Me podrían decir como quedaría el borrarPelicula? Porque intente con un split sacar el id de ese arreglo para poder pasárselo, pero no funciona. Gracias!
`function borrarPelicula(){
    
    var arreglo = table.getSelectedRows();  
    var separadores = [':',','];
    var id = arreglo[0].split(separadores);
    console.log(id);
     //movieService.deleteMovie(id);

    }    `

**Comment by RodrigoJacznik** [comment]
Hola, no necesitas usar split. Para obtener el id tenes que hacer:

```javascript
var id = arreglo[0].id;
```

```javascript
function borrarPelicula(){
    var arreglo = table.getSelectedRows();  
    var id = arreglo[0].id;
    console.log(id);
     //movieService.deleteMovie(id); 
}
```

Saludos.
