### ISSUE TITLE
Consulta sobre nueva release

### ISSUE THREAD

**Issue by azamma** [frlp-utn-ingsoft/filmster#34]
Buenas,

Acabamos de finalizar el punto opcional 1 que nos había quedado pendiente. Queríamos saber si tenemos que realizar una nueva release o si directamente lo mergeamos al dev para que quede para la siguiente actividad.

Saludos!

**Comment by ivanduva** [comment]
Buenísimo! 
Hagan una release, sería la versión 1.3.0, si seguimos el versionado semántico (https://semver.org/)

Saludos!

**Comment by azamma** [comment]
Excelente! Vamos a hacer eso. Saludos!
