### ISSUE TITLE
Problema con pulleo

### ISSUE THREAD

**Issue by azamma** [frlp-utn-ingsoft/filmster#42]
Buenas,

En esta última actividad me encontré con dos problemas en mi repositorio local que no me son un impedimento para realizar la tarea pero que me gustaría averiguar a qué se debe. 

1 - Uno de mis compañeros terminó realizando el "git pull filmster master" porque yo no podía, me decía que el repositorio no existe. Luego probé reemplazando filmster por el enlace del repositorio de ustedes y ahí sí anduvo. Me gustaría comprender por qué me pasa a mí, y no al resto de mi grupo.

2 - Una vez que lo antes mencionado fue realizado por uno de mis compañeros, cuando pulleé para actualizar mi repo local me encontré con otro problema: mi rama máster no se encontraba actualizada, pero mi rama dev sí. O sea, en la dev tengo incluido la carpeta test y todo lo nuevo pero en la máster no. Al resto de mi grupo parece haberle funcionado bien.

Al inicio dije que no me era un impedimento porque tranquilamente trabajo en la branch dev con la feature que se me asignó y listo, pero me gustaría entender por qué me está pasando esto puntualmente a mí. Probé borrando el repo local y clonando de nuevo y luego pulleando pero nada. Perdón la extensión.

Saludos!

**Comment by RodrigoJacznik** [comment]
Hola, no hay problema con la extensión del issue.

1. el comando `git pull filmster master` se traduce como: bájame el código del branch master del remote filmster.
Es probable que no tengas ese remote configurado. Esto lo podes comprobar ejecutando `git remote -v`, seguro que existe `origin` nada mas.
Tus compañeros lo deben haber agregado con el comando `git remote add [nombre] [url]`. Te dejo mas info al respecto: https://git-scm.com/book/es/v1/Fundamentos-de-Git-Trabajando-con-repositorios-remotos

2. Cuando ejecutas `git pull` solo lo realiza sobre el branch en el que estas "parado". Es probable que si te pasas a `master` y haces `git pull` vas a ver los cambios. Si no pasa eso lo volvemos a revisar. Una de las chances esta en que ninguno de tus compañero pusheo `master` despues de actualizar con respecto a filmster

Saludos

**Comment by azamma** [comment]
Buenísimo, todo resuelto.

El inconveniente con la rama máster fue efectivamente que no había sido pusheada. Gracias.

Saludos.
