### ISSUE TITLE
El test que me tocó está resuelto

### ISSUE THREAD

**Issue by azamma** [frlp-utn-ingsoft/filmster#44]
Buenas de nuevo,

Estaba por intentar resolver el test que me tocó y me encuentro con que está resuelto. El inciso que me tocó es el 3 y dice: 

> Hacer un test que pruebe que, luego de obtener todas las películas por API, el array
que se obtiene es vacío.

Y luego me encontré con este código que era más o menos lo que pensaba realizar:

```
 test('Se debería iniciar la aplicación sin películas', async () => {
    const URL = `${baseURL}/movies`;
    const req = await fetch(URL);
    const movies = await req.json();
    expect(movies.length).toBe(0);
 });
```

La verdad no sé si era un punto que la idea era darse cuenta que ya estaba o si me tienen que asignar otra tarea. Espero su respuesta.

Saludos!

**Comment by RodrigoJacznik** [comment]
Hola, te asigne otra tarea. Te lo mande por email.
Gracias por avisar. Saludos

**Comment by azamma** [comment]
Buenísimo. Nos llegó el mail.
Saludos.
