### ISSUE TITLE
Error al hacer npm run test

### ISSUE THREAD

**Issue by redBaron23** [frlp-utn-ingsoft/filmster#45]
Hola cuando trato de hacer npm run test (todavia no hice ninguno) me salta esto

![image](https://user-images.githubusercontent.com/23110463/57953040-62069600-78c5-11e9-8c47-d88947e2c852.png)

55Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@6.9.0
3 info using node@v11.15.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle filmster@1.0.0~pretest: filmster@1.0.0
6 info lifecycle filmster@1.0.0~test: filmster@1.0.0
7 verbose lifecycle filmster@1.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle filmster@1.0.0~test: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/redbaron/myBuilds/filmster/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle filmster@1.0.0~test: CWD: /home/redbaron/myBuilds/filmster
10 silly lifecycle filmster@1.0.0~test: Args: [ '-c', 'jest' ]
11 silly lifecycle filmster@1.0.0~test: Returned: code: 1  signal: null
12 info lifecycle filmster@1.0.0~test: Failed to exec test script
13 verbose stack Error: filmster@1.0.0 test: `jest`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid filmster@1.0.0
15 verbose cwd /home/redbaron/myBuilds/filmster
16 verbose Linux 4.19.36-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
18 verbose node v11.15.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error filmster@1.0.0 test: `jest`
22 error Exit status 1
23 error Failed at the filmster@1.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by RodrigoJacznik** [comment]
Hola, el error es que falla un test

**Comment by redBaron23** [comment]
> Hola, el error es que falla un test

Si, pero el problema es que ninguno de nosotros hizo ningun test todavia, son los que clonamos los que estan, y le comente a otro alumno y le pasa lo mismo

**Comment by redBaron23** [comment]
Aca dejo los test que son 
![image](https://user-images.githubusercontent.com/23110463/57960451-25479880-78df-11e9-9c16-8e6b11e7f253.png)

**Comment by RodrigoJacznik** [comment]
Volve a actualizar el proyecto con respecto a filmster y se debería solucionar.

**Comment by redBaron23** [comment]
> Volve a actualizar el proyecto con respecto a filmster y se debería solucionar.

Perfecto
