### ISSUE TITLE
Test no anda

### ISSUE THREAD

**Issue by nikosanarg** [frlp-utn-ingsoft/filmster#48]
Uno de los tests que vienen (no de los que se nos dieron de ejercicio) falla

![Screenshot_1](https://user-images.githubusercontent.com/46543492/57959982-c6811f80-78dc-11e9-814f-c1e2ed52cf17.jpg)

El código es el siguiente, conste que todavía no lo toqué

_test('Se debería poder seleccionar una película', async () => {
    const movie = {
        title: 'Back to the Future',
        description: 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.',
        year: 1985,
        runtime: 116,
        country: 'United States',
        language: 'English',
        genres: ['Adventure', 'Comedy', 'Science Fiction'],
        directors: ['Robert Zemeckis'],
        writers: ['Robert Zemeckis', 'Bob Gale']
    };

    await fetch(`${baseURL}/api_/v1/movies`, {
        method: 'POST',
        body: JSON.stringify(movie),
        headers:{
            'Content-Type': 'application/json'
        }
    });

    await page.reload();
    const rows = await page.$$('table#movies tbody tr');

    expect(rows.length).toBe(1);

    await page.$eval('table#movies tbody tr td:nth-child(1) input', firstCheck => firstCheck.click());
    const selectedRows = await page.evaluate(() => window.table.getSelectedRows());
    expect(selectedRows.length).toBe(1);
    expect(selectedRows[0].title).toBe(movie.title);
})

**Comment by nikosanarg** [comment]
Probé cambiar de rama y volver al master por si había pulleado mal pero parece que lo clonaron así, ¿cómo sugieren proceder?

**Comment by redBaron23** [comment]
> Probé cambiar de rama y volver al master por si había pulleado mal pero parece que lo clonaron así, ¿cómo sugieren proceder?

Crea tu branch de test y hace el tuyo amigo, yo hice lo mismo

**Comment by RodrigoJacznik** [comment]
Actualiza master con respecto a filmster y se soluciona o ponele `skip` despues de `test`. Nos quedado mal ese test.
De todas formas no hay problema si lo dejan así. No es parte de la corrección.

**Comment by nikosanarg** [comment]
> > Probé cambiar de rama y volver al master por si había pulleado mal pero parece que lo clonaron así, ¿cómo sugieren proceder?
> 
> Crea tu branch de test y hace el tuyo amigo, yo hice lo mismo

Se, estaba en eso pero la curiosidad mató al gato, probé los tests en mi rama y 2 fallaron, volví al master y fallaron 3, lo resolví yéndome a dormir

> Actualiza master con respecto a filmster y se soluciona o ponele `skip` despues de `test`. Nos quedado mal ese test.
> De todas formas no hay problema si lo dejan así. No es parte de la corrección.

De una, me verán volver por estos pagos entonces

**Comment by nikosanarg** [comment]
Ahora andan todos, espero no hacer explotar todo, gracias.
