### ISSUE TITLE
Duda merge dev

### ISSUE THREAD

**Issue by redBaron23** [frlp-utn-ingsoft/filmster#51]
Hola, 
1)Ya hice mi test y anda, deberia hacer el merge a dev ahora, o cuando mi equipo haga el resto?
2)Tengo que hacer un punto en el cual tengo que arreglar esto:
```text
El test incluido en test/unit/ui.test.js falla, demostrando que hay un bug en la app.
Solucionar este bug (para esta tarea, hay que quitar el “skip” incluido al principio del
código del test).
```
Deberia crear un branch hotFix y hacer como veniamos haciendo, o deberia usar bugFix? de ser bugFix, la conexion seria solo con dev?, ejemplo arreglo el bug desde bugFix y hago:
```bash
git checkout dev
git merge bugFix
```

**Comment by redBaron23** [comment]
> Hola,
> 1)Ya hice mi test y anda, deberia hacer el merge a dev ahora, o cuando mi equipo haga el resto?
> 2)Tengo que hacer un punto en el cual tengo que arreglar esto:
> 
> ```
> El test incluido en test/unit/ui.test.js falla, demostrando que hay un bug en la app.
> Solucionar este bug (para esta tarea, hay que quitar el “skip” incluido al principio del
> código del test).
> ```
> 
> Deberia crear un branch hotFix y hacer como veniamos haciendo, o deberia usar bugFix? de ser bugFix, la conexion seria solo con dev?, ejemplo arreglo el bug desde bugFix y hago:
> 
> ```shell
> git checkout dev
> git merge bugFix
> ```

Con respecto al punto 2 el error es este:

```javascript
export function parseCSV(val) {
    return val.split(',').flatMap(v => v.split());
}
```
deberia ser asi? 
```javascript
val.split(', ')
```
El test es el siguiente deberia el test mandar "item1,item2" o si manda "item1, item2" deberia andar igual?:
```javascript
const utils = require('../../client/src/utils.mjs');

test('parseCSV', () => {
    const actual = utils.parseCSV('foo, bar')
    const expected = ['foo', 'bar']

    expect(actual).toStrictEqual(expected)
})
```

**Comment by RodrigoJacznik** [comment]
Hola.
Cuando termines tu test hace el merge a dev.

Con respecto al opcional, los siguientes casos:

<pre>
-  '         foo, bar'
-  'foo,bar'
-  'foo,    bar'
-  'foo, bar       '
</pre>

Deberian retornar `['foo', 'bar']`. Tu solución no contempla todos estos casos. Podes usar la funcion trim (https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/String/Trim)

Hace un branch bugfix. Los hotfix son solo desde master.

**Comment by redBaron23** [comment]
> Hola.
> Cuando termines tu test hace el merge a dev.
> 
> Con respecto al opcional, los siguientes casos:
> 
> -  '         foo, bar'
> -  'foo,bar'
> -  'foo,    bar'
> -  'foo, bar       '
> 
> Deberian retornar `['foo', 'bar']`. Tu solución no contempla todos estos casos. Podes usar la funcion trim (https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/String/Trim)
> 
> Hace un branch bugfix. Los hotfix son solo desde master.

Ah perfecto con un replace(" ","") ya andaria no ?

**Comment by RodrigoJacznik** [comment]
no, creo que hay algunos casos que no los toma.
Hace el split como esta ahora y por cada item en el array que te retorna usa trim

**Comment by redBaron23** [comment]
> no, creo que hay algunos casos que no los toma.
> Hace el split como esta ahora y por cada item en el array que te retorna usa trim

Te molesto de nuevo, estara bien asi?

```javascript
export function parseCSV(val) {
    return val.split(',').flatMap(v => v.split()).map(item => item.trim());
}

```
porque ahora me pasa el test que lo modifique asi:

```javascript
const utils = require('../../client/src/utils.mjs');

test('parseCSV', () => {
    const actual = utils.parseCSV('  foo  , bar  ')
    const expected = ['foo', 'bar']

    expect(actual).toStrictEqual(expected)
})

```

Y me tira esto la consola:

![image](https://user-images.githubusercontent.com/23110463/57962324-c89eaa80-78eb-11e9-8a47-a5cc292e61b5.png)

**Comment by RodrigoJacznik** [comment]
Si, esta bien resuelto.

El error que te tira es en otro test, actualiza con respecto a filmster o ignoralo (ponele skip despues de test para que no te salte en consola)

**Comment by redBaron23** [comment]
Dale , igual se arreglo solo. Osea es medio casual si hago npm run test una vez atras de la otra, a veces pasa sin problemas y otras veces tiene problemas en alguno de estos test:
(adjunto otros 2 errores que tiro)
![image](https://user-images.githubusercontent.com/23110463/57963076-68ad0180-78f5-11e9-9d9f-751196c0fd37.png)
![image](https://user-images.githubusercontent.com/23110463/57963089-a7db5280-78f5-11e9-9c7d-f964aabfcdd8.png)

Igual ya fue mi test anda, gracias!
