### ISSUE TITLE
Duda test opcional

### ISSUE THREAD

**Issue by redBaron23** [frlp-utn-ingsoft/filmster#54]
Hola de nuevo, este test opcional seria e2e, y mi duda es, esta bien codigo del test o habria que verificar que la pelicula este en la db? de ser asi como obtengo el id de esta pelicula?

```text
Realizar un test que pruebe la funcionalidad completa de agregar un usuario desde
el cliente.
```

```javascript
test('Se deberia poder agregar una pelicula' , async () => {
	const movie = {
        title: 'El dia que me quieras',
        description: 'Carlos Argüelles is the son of a wealthy man whose only interests in life are business and making money. While trying to succeed in show business he falls in love with a dancer and they elope to marry. But success is not easy to obtain.',
        year: 1935,
        runtime: 82,
        country: 'United States',
        language: 'Spanish',
        genres: ['Drama'],
        directors: ['John Reinhardt'],
        writers: ['Alfredo Le Pera']
    };
	await fetch(`${baseURL}/api/v1/movies`, {
        method: 'POST',
        body: JSON.stringify(movie),
        headers:{
            'Content-Type': 'application/json'
        }
    });
    await page.reload();
    const rows = await page.$$('table#movies tbody tr');

    await page.$eval('table#movies tbody tr td:nth-child(1) input', firstCheck => firstCheck.click());
    const selectedRows = await page.evaluate(() => window.table.getSelectedRows());
    expect(selectedRows[0].title).toBe(movie.title);
})
```

**Comment by RodrigoJacznik** [comment]
Hola, no esta bien porque la película la estas creando por api.
Los pasos del test serian los siguientes:

1. Hacer click en el botón agregar película
2. Llenar el formulario con los datos de la película
3. Hacer click en el botón guardar
4. Comprobar que la tabla tenga la nueva película

En este test vos tenes que ignorar detalles de implementación (el fetch) y escribirlo como si fueras el usuario de la app.

**Comment by redBaron23** [comment]
> Hola, no esta bien porque la película la estas creando por api.
> Los pasos del test serian los siguientes:
> 
>     1. Hacer click en el botón agregar película
> 
>     2. Llenar el formulario con los datos de la película
> 
>     3. Hacer click en el botón guardar
> 
>     4. Comprobar que la tabla tenga la nueva película
> 
> 
> En este test vos tenes que ignorar detalles de implementación (el fetch) y escribirlo como si fueras el usuario de la app.

Gracias!
