### ISSUE TITLE
Test opcional 1

### ISSUE THREAD

**Issue by redBaron23** [frlp-utn-ingsoft/filmster#55]
> Hola, no esta bien porque la película la estas creando por api.
> Los pasos del test serian los siguientes:
> 
>     1. Hacer click en el botón agregar película
> 
>     2. Llenar el formulario con los datos de la película
> 
>     3. Hacer click en el botón guardar
> 
>     4. Comprobar que la tabla tenga la nueva película
> 
> 
> En este test vos tenes que ignorar detalles de implementación (el fetch) y escribirlo como si fueras el usuario de la app.

Gracias!
Al final no me fue tan facil, como hago para hacer referencia a cada elemento desde el codigo? ejemplo probe asi desde la consola (usando jquery) y anduvo pero en el codigo me tira error.
```javascript
$("#addMovieBtn").click();
```
_Originally posted by @redBaron23 in https://github.com/frlp-utn-ingsoft/filmster/issues/54#issuecomment-493683213_

**Comment by RodrigoJacznik** [comment]
Algo así
`await page.$eval('#addMovieBtn', btn => btn.click());`

**Comment by redBaron23** [comment]
> Algo así
> `await page.$eval('#addMovieBtn', btn => btn.click());`

Ahora si gracias, ahi lei bien el email no habia visto la documentacion
