### ISSUE TITLE
Sobre el test opcional

### ISSUE THREAD

**Issue by azamma** [frlp-utn-ingsoft/filmster#60]
Buenas noches,

El test opcional que pide probar la funcionalidad completa de crear un usuario requiere que modifiquemos la base de datos, crear el modelo del usuario y demás? De cumplirse eso, con "probar de forma completa" se refieren a crearlo desde la API?

Saludos.

**Comment by RodrigoJacznik** [comment]
Hola, se refiere a que hay que probar la interfaz de usuario también. 
Si lo creas por API no estarías probando que el modal y el formulario funcionan. Tenes que abrir el modal, llenar el formulario y apretar en el boton guardar.

**Comment by azamma** [comment]
Perfecto. Y de paso pregunto, con respecto al opcional2 al tratarse de un quitar el "skip" que es un bug es para que hagamos un hotfix cierto?

**Comment by RodrigoJacznik** [comment]
Si, o un fix común. Como prefieran

**Comment by azamma** [comment]
Genial. Por último para poder cerrar bien el opcional de crear usuario. La idea entonces es crear también en la ui el botón "agregar usuario", el modal, etc? Porque no venía incluido en el update de master. Pregunto por si tenía que estar o si la tarea opcional además consiste en que los creemos.

**Comment by RodrigoJacznik** [comment]
No, fue error de tipeo. No es usuario, es película

**Comment by azamma** [comment]
Ya parecía algo extenso ese opcional jaja, lo bueno es que se aprendió a crear nuevos modelos en la db y a asignar las rutas para la API de usuario. Pero me siento más imbécil por no haberme dado cuenta que era mucho más probable que fuera un error de tipeo antes de arrancarlo. Consulté por cosas más obvias jajaj Saludos.

**Comment by RodrigoJacznik** [comment]
Uff, perdón, pensé que se entendía que era un error.
