### ISSUE TITLE
Gitflow

### ISSUE THREAD

**Issue by redBaron23** [frlp-utn-ingsoft/filmster#9]
Hola mi duda seria, cuando hablan de gitflow, la idea es hacerlo con el siguiente repositorio?([https://github.com/nvie/gitflow](url)

**Comment by RodrigoJacznik** [comment]
Hola
No, la idea es seguir las practicas de gitflow sin ninguna extensión.

nvie/gitflow es una extensión que facilita la practica pero con Ivan creemos que es mejor aprender esta forma de trabajo sin ninguna herramienta extra.

Saludos.

**Comment by redBaron23** [comment]
Perfecto muchas gracias!

Saludos
